export const SET_API_URL = "SET_API_URL";
export const SET_CONTACTS_DETAILS = "SET_CONTACTS_DETAILS";
export const SET_OTPS_DETAILS = "SET_OTPS_DETAILS";
export const RESET_STATE_OF_MESSAGE_BODY = "RESET_STATE_OF_MESSAGE_BODY"
export const SET_MESSAGE_BODY = "SET_MESSAGE_BODY";
export const SET_GET_ALL_DATA_FLAG = "SET_GET_ALL_DATA_FLAG";
